const Constant = {
 APP_NAME: 'SIJAA',
 ACTIVE_MENU: 'ACTIVE_MENU'  ,
 
//  MENU
MENU_DASHBOARD:'DASHBOARD',
MENU_CUSTOMER:'CUSTOMER',
MENU_PRODUCT:'PRODUCT',
MENU_STOCK:'STOCK',
MENU_CONTACT:'CONTACT',

// AUTH
TOKEN: 'TOKEN'
}

export default Constant